name: campus_mobile_experimental
description: Mobile app platform for campus.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  app_settings: ^4.1.1
  barcode_widget: ^2.0.2
  beacon_broadcast: 0.3.0
  connectivity: 3.0.6
  device_info: ^2.0.3
  dio: ^4.0.4
  dots_indicator: ^2.1.0
  encrypt: ^5.0.1
  firebase_analytics: ^9.1.1
  firebase_core: ^1.13.0
  firebase_crashlytics: ^2.5.2
  firebase_messaging: ^11.2.7
  flutter:
    sdk: flutter
  flutter_scandit_plugin:
    git:
      url: https://github.com/UCSD/flutter_scandit.git
      ref: 41fb666299ed90d8277c24e0065149e83cd71494
  flutter_blue:
    git:
      url: https://github.com/UCSD/flutter_blue.git
      ref: 470b128cd463373d0ec4b668d5b4f449dc728d72
  flutter_linkify: 5.0.2
  flutter_local_notifications: ^9.3.2
  flutter_secure_storage: 5.0.2
  flutter_sticky_header: 0.6.0
  get: ^4.6.1
  google_maps_flutter: ^2.1.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  intl: 0.17.0
  liquid_progress_indicator:
    git:
      url: https://github.com/UCSD/liquid_progress_indicator.git
      ref: 9fd5cc0aa1a68d70588741f40bfc6830b46c10c1
  location: ^4.3.0
  package_info: 2.0.2
  percent_indicator: ^4.0.0
  permission_handler: ^9.2.0
  pointycastle: ^3.5.1
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  uni_links2: 0.6.0+2
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  webview_flutter: ^3.0.1
  wifi_connection: 0.0.4
dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/public_key.txt
