name: campus_mobile_experimental
description: Mobile app platform for campus.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  app_settings: 4.1.0
  barcode_widget: 2.0.1
  beacon_broadcast: 0.3.0-nullsafety.0
  connectivity: 3.0.6
  device_info: 2.0.2
  dio: 4.0.0
  dots_indicator: 2.0.0
  encrypt: 5.0.0
  firebase_analytics: 8.1.0
  firebase_core: 1.2.0
  firebase_crashlytics: 2.0.4
  firebase_messaging: 10.0.0
  flutter:
    sdk: flutter
  flutter_scandit_plugin:
    git:
      url: https://github.com/UCSD/flutter_scandit.git
      ref: 41fb666299ed90d8277c24e0065149e83cd71494
  flutter_blue:
    git:
      url: https://github.com/UCSD/flutter_blue.git
      ref: 470b128cd463373d0ec4b668d5b4f449dc728d72
  flutter_linkify: 5.0.2
  flutter_local_notifications: 8.2.0
  flutter_secure_storage: 4.2.0
  flutter_sticky_header: 0.6.0
  get: 4.1.4
  google_maps_flutter: 2.0.6
  hive: 2.0.4
  hive_flutter: 1.0.0
  intl: 0.17.0
  liquid_progress_indicator:
    git:
      url: https://github.com/UCSD/liquid_progress_indicator.git
      ref: 9fd5cc0aa1a68d70588741f40bfc6830b46c10c1
  location: 4.1.1
  package_info: 2.0.2
  percent_indicator: 3.0.1
  permission_handler: 7.1.0
  pointycastle: 3.4.0
  provider: 6.0.1
  shared_preferences: 2.0.6
  uni_links2: 0.6.0+2
  url_launcher: 6.0.6
  uuid: 3.0.4
  webview_flutter: 2.0.8
  wifi_connection: 0.0.4
dev_dependencies:
  build_runner: 2.0.2
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/public_key.txt
