name: campus_mobile_experimental
description: Mobile app platform for campus.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  barcode_widget: 2.0.3
  connectivity: 3.0.6
  dio: 4.0.6
  encrypt: 5.0.1
  dots_indicator: 2.1.0
  firebase_analytics: 8.1.0
  firebase_core: 1.2.0
  firebase_crashlytics: 2.0.4
  firebase_messaging: 10.0.0
  flutter:
    sdk: flutter
  flutter_scandit_plugin:
    git:
      url: https://github.com/UCSD/flutter_scandit.git
      ref: scandit-6.6.3
  flutter_linkify: 5.0.2
  flutter_local_notifications: 9.9.1
  flutter_secure_storage: 5.0.2
  flutter_sticky_header: 0.6.0
  get: 4.1.4
  google_maps_flutter: 2.2.2
  hive: 2.0.4
  hive_flutter: 1.0.0
  intl: 0.17.0
  liquid_progress_indicator:
    git:
      url: https://github.com/UCSD/liquid_progress_indicator.git
      ref: 9fd5cc0aa1a68d70588741f40bfc6830b46c10c1
  geolocator: ^9.0.2
  package_info: 2.0.2
  percent_indicator: 4.2.2
  permission_handler: ^10.2.0
  pointycastle: 3.4.0
  provider: 6.0.1
  shared_preferences: 2.0.6
  uni_links2: 0.6.0+2
  url_launcher: 6.0.6
  webview_flutter: 2.0.8
  wifi_connection:
    git:
      url: https://github.com/UCSD/wifi_connection.git
      ref: 179eb3a322b9d947752b4ff4e810582c3e262e47
  audio_service: ^0.18.9
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  device_info_plus: ^9.1.2
dev_dependencies:
  build_runner: 2.0.2
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.0
dependency_overrides:
  firebase_core_platform_interface: 4.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/public_key.txt