name: campus_mobile_experimental
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  app_settings: 4.0.4
  background_fetch: 0.6.0
  barcode_widget: 1.5.0
  beacon_broadcast: 0.2.1
  device_info: 0.4.2+8
  dio: 3.0.10
  dots_indicator: 1.2.0
  encrypt: 4.0.3
  firebase_analytics: ^7.0.1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_messaging: ^8.0.0-dev.14
  flutter_scandit_plugin:
    git:
      url: https://github.com/UCSD/flutter_scandit.git
      ref: master
  flutter_blue:
    git:
      url: https://github.com/UCSD/flutter_blue.git
      ref: master
  flutter_linkify: 3.1.3
  flutter_secure_storage: 3.3.1+1
  flutter_sticky_header: 0.4.0
  flutter:
    sdk: flutter
  google_maps_flutter: 1.0.2
  hive_flutter: 0.3.1
  hive: 1.4.4+1
  intl: 0.16.0
  location: 3.0.2
  package_info: 0.4.0+18
  path_provider: 1.6.8
  pointycastle: 1.0.2
  provider: 4.0.5
  shared_preferences: 0.5.6+3
  url_launcher: 5.2.5
  uuid: 2.2.0
  permission_handler: 5.1.0+2
  webview_flutter:
    git:
      path: packages/webview_flutter
      ref: webview-transparent-background
      url: "git://github.com/crizant/plugins"
  uni_links: 0.4.0
dev_dependencies:
  hive_generator: 0.8.1
  build_runner: 1.10.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/public_key.txt